export const FETCH_TRANSACTIONS = 'FETCH_TRANSACTIONS';
export const SET_WALLET_ADDRESS = 'SET_WALLET_ADDRESS';
export const SET_AMOUNT = 'SET_AMOUNT';
export const SET_ERRORS = 'SET_ERRORS';
export const ADD_NEW_TRANSACTION = 'ADD_NEW_TRANSACTION';
export const SHOW_TRANSACTION_FORM = 'SHOW_TRANSACTION_FORM';
export const HIDE_TRANSACTION_FORM = 'HIDE_TRANSACTION_FORM';
export const GET_CRYPTO_PRICE = 'GET_CRYPTO_PRICE';
